// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbAwxivLIj-QQx4N4Wd4mYrd3vXyojWss',
    appId: '1:736430912123:web:646936755a4980ba8028de',
    messagingSenderId: '736430912123',
    projectId: 'colorblock-2f41c',
    authDomain: 'colorblock-2f41c.firebaseapp.com',
    storageBucket: 'colorblock-2f41c.firebasestorage.app',
    measurementId: 'G-7Q3BX3QSE8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKo-IuV4VRoAB9DQDPqSAyJvdkPXEhWe8',
    appId: '1:736430912123:android:947591613ce75bd08028de',
    messagingSenderId: '736430912123',
    projectId: 'colorblock-2f41c',
    storageBucket: 'colorblock-2f41c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBISVj7-4Q_cKOWQicwpoJcREOPN9kKFts',
    appId: '1:736430912123:ios:4ee33c9023400e328028de',
    messagingSenderId: '736430912123',
    projectId: 'colorblock-2f41c',
    storageBucket: 'colorblock-2f41c.firebasestorage.app',
    iosBundleId: 'com.colorblockbaster.org',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBISVj7-4Q_cKOWQicwpoJcREOPN9kKFts',
    appId: '1:736430912123:ios:fd51b721e80a3a608028de',
    messagingSenderId: '736430912123',
    projectId: 'colorblock-2f41c',
    storageBucket: 'colorblock-2f41c.firebasestorage.app',
    iosBundleId: 'com.example.colorBlock',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbAwxivLIj-QQx4N4Wd4mYrd3vXyojWss',
    appId: '1:736430912123:web:04356c2abf90be5c8028de',
    messagingSenderId: '736430912123',
    projectId: 'colorblock-2f41c',
    authDomain: 'colorblock-2f41c.firebaseapp.com',
    storageBucket: 'colorblock-2f41c.firebasestorage.app',
    measurementId: 'G-SNHNFZF1CN',
  );
}
